CREATE DATABASE pern_wishlist;

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255)
);

DROP TABLE IF EXISTS wishlists CASCADE;
CREATE TABLE wishlists (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE NOT NULL
);

DROP TABLE IF EXISTS items  CASCADE;
CREATE TABLE items (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  url VARCHAR,
  img_url VARCHAR,
  price INT,
  wishlist_id INTEGER NOT NULL REFERENCES wishlists(id) ON DELETE CASCADE NOT NULL
);